version: '3.8'

services:
  client:
    build:
      context: . # path to directory of dockerfile
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"  # Docker host port : port in container

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000" 
