FROM python:3.10.13
WORKDIR /usr/src/server
COPY server/ ./
RUN pip install --no-cache-dir -r requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

# Run these two commands if you want to run as separate container
#  - docker build -f Dockerfile.server -t fastapi:1.0.0 .
#  - docker run -it -p 8000:8000 fastapi:1.0.0
