version: '3.8'

services:
  client:
    build:
      context: . # path to directory of dockerfile
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"  # Docker host port : port in container
    volumes: # For persisting data if required
      - ./client:/usr/src/client

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000" 
    volumes:
      - ./server:/usr/src/server
