version: '3'
services:
  server:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    environment:
    command:  bash -c "uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
    volumes:
      - postgres-db:/var/lib/postgresql/data 
  
volumes:
  