FROM node:18.16.0
WORKDIR /usr/src/client
COPY client/ ./
RUN npm install
CMD ["npm", "run", "dev"] 

# Run these two commands if you want to run as separate container
#  - docker build -f Dockerfile.server -t reactapp:1.0.0 .
#  - docker run -it -p 8080:8080 reactapp:1.0.0

# Go to localhost:8080 to use the application